# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/web_monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsrc/proto/web_monitor.proto\"\xa2\x01\n\x10WebMonitorResult\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x11\n\tsucceeded\x18\x02 \x01(\x08\x12\x15\n\rresponse_code\x18\x03 \x01(\x05\x12\x1c\n\x14request_time_seconds\x18\x04 \x01(\x02\x12\x13\n\x0bregex_check\x18\x05 \x01(\x08\x12\x1a\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x06.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"\x1e\n\x05\x45rror\x12\x15\n\rerror_message\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.web_monitor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WEBMONITORRESULT']._serialized_start=32
  _globals['_WEBMONITORRESULT']._serialized_end=194
  _globals['_ERROR']._serialized_start=196
  _globals['_ERROR']._serialized_end=226
# @@protoc_insertion_point(module_scope)
